# Generated by Django 3.2.9 on 2021-11-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut Medico'),
        ),
    ]
