# Generated by Django 3.2.9 on 2021-11-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_agenda_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='idagenda',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero Telefonico'),
        ),
    ]
