# Generated by Django 3.2.9 on 2021-11-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_citas_idagenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='comprobante',
        ),
        migrations.AddField(
            model_name='pago',
            name='nombrecliente',
            field=models.CharField(default=1, max_length=50, verbose_name='Nombre Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut Medico'),
        ),
        migrations.DeleteModel(
            name='Informes',
        ),
    ]
