# Generated by Django 3.2.9 on 2022-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211126_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('idespacio', models.IntegerField(primary_key=True, serialize=False, verbose_name='ESPACIO ID')),
                ('pago', models.CharField(max_length=50, verbose_name='Pago $')),
                ('horario', models.CharField(max_length=50, null=True, verbose_name='HORARIO DIA/HORA')),
                ('tipoespacio', models.CharField(max_length=10, verbose_name='ESPACIO')),
            ],
        ),
        migrations.CreateModel(
            name='Gastocomun',
            fields=[
                ('idgastocomun', models.IntegerField(primary_key=True, serialize=False, verbose_name='GASTO COMUN ID')),
                ('mes', models.CharField(max_length=10, verbose_name='MES')),
                ('nombreresidente', models.CharField(max_length=50, verbose_name='NOMBRE RESIDENTE')),
                ('precio', models.IntegerField(verbose_name='Precio $')),
            ],
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='citas',
            old_name='idagenda',
            new_name='idespacio',
        ),
        migrations.AlterField(
            model_name='citas',
            name='hora',
            field=models.CharField(max_length=50, verbose_name='Confirmar Hora y Dia Tomada'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='run',
            field=models.CharField(max_length=10, verbose_name='Rut Residente'),
        ),
    ]
