# Generated by Django 3.2.9 on 2022-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220515_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='run',
            field=models.CharField(max_length=50, verbose_name='Rut Residente'),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='tipoespacio',
            field=models.CharField(max_length=50, verbose_name='ESPACIO'),
        ),
        migrations.AlterField(
            model_name='gastocomun',
            name='mes',
            field=models.CharField(max_length=50, verbose_name='MES'),
        ),
    ]
